name: bens-pred2
repo: https://github.com/deep-horizon/customer_example2.git
model: data/model.ckpt
create_dataset: src.dataset:create
train: src.model:train
test: src.model:test
predict: src.model:predict