name: pricing

repo: https://github.com/deep-horizon/customer_example2.git

model: data/model.ckpt

prepro_data: src.dataset:prepro

train: src.model:train

test: src.model:test

predict: src.model:predict